<pre>
<?php //print_r($this->data); die();?>
</pre>

<style>
table {
	border-spacing: 0;
}
td {
	padding: 5px;
}
</style>
<div align="center">
<h3>Список клиентов</h3>

<table border=1>
    <tr valign="bottom" align="center">
        <td><b>Наименование</b></td>
        <td><b>Описание</b></td>
    </tr>
        <?php foreach ($this->data as $row) :?>
            <tr>
                <td><?=$row['name']?></td>
                <td><?=$row['description']?></td>
            </tr>
        <?php endforeach;?>
</table>
</div>