<pre>
<?php //print_r($this->data); die;
$currency = new Zend_Currency('ru_RU');
$total_success = 0;
$total_added = 0;
$total_count = 0;
?>
</pre>

<style>
table {
	border-spacing: 0;
}
td {
	padding: 5px;
}
</style>
<div align="center">
<h3>
    Отчёт о деятельности менеджеров за период
    с <?
        $date = @date_create($this->data['start']);
        echo !$date ? '' : $date->format(OSDN_DATE_DISPLAY_FORMAT);
    ?>
    по <?
        $date = @date_create($this->data['end']);
        echo !$date ? '' : $date->format(OSDN_DATE_DISPLAY_FORMAT);
    ?>
</h3>
<?php if (!empty($this->data['summary'])): ?>
<table border=1>
    <tr valign="bottom" align="center">
        <td><b>Менеджер</b></td>
        <td><b>Сумма выполненных заказов <br /> Рубль РФ</b></td>
        <td><b>Сумма добавленных заказов <br /> Рубль РФ</b></td>
        <td><b>Количество <br />просроченных заказов</b></td>
    </tr>
        <?php foreach ($this->data['summary'] as $row) :?>
        <?php
            $total_success  += $row['summ_success'];
            $total_added    += $row['summ_added'];
            $total_count    += $row['failed_count'];
        ?>
            <tr>
                <td><?=$row['name']?></td>
                <td align="right"><?=$currency->toCurrency($row['summ_success'])?></td>
                <td align="right"><?=$currency->toCurrency($row['summ_added'])?></td>
                <td align="right"><?=$row['failed_count']?></td>
            </tr>
        <?php endforeach;?>
    <tr valign="bottom" align="right">
        <td align="left"><b>ИТОГО</b></td>
        <td><b><?=$currency->toCurrency($total_success)?></b></td>
        <td><b><?=$currency->toCurrency($total_added)?></b></td>
        <td><b><?=$total_count?></b></td>
    </tr>
</table>
<?php endif; ?>
</div>