<pre>
<?php //print_r($this->data); //die;?>
</pre>

<style>
body {
    font-size: small;
}
.address {
    width: 150px;
    height: 20px;
    overflow: hidden;
    display: block;
    cursor: help;
}
.square {
    border: 1px solid grey;
    width: 20px;
}
.x-row-waiting {
    background: #FFFF80;
}
.x-row-payed {
    background: #99CC00;
}
.x-row-paymentdelayed {
    background: #FF8080;
}
</style>

<table id="legend" cellspacing="0" cellpadding="0" border="0"><tr>
<td><b>Условные обозначения:&nbsp;</b></td>
<td class="square x-row-payed">&nbsp;</td><td>&nbsp;Оплачено&nbsp;</td>
<td class="square x-row-waiting">&nbsp;</td><td>&nbsp;Ожидается&nbsp;</td>
<td class="square x-row-paymentdelayed">&nbsp;</td><td>&nbsp;Задерживается&nbsp;</td>
</tr></table>

<center>
<h3>ГРАФИК ПЛАТЕЖЕЙ</h3>
</center>
<?php if (!empty($this->data['list']) && !empty($this->data['dates'])): ?>
<?php $totalCost = $totalPayed = $totalRest = 0; ?>
<table cellspacing="0" cellpadding="5" border="1">
    <tr valign="middle" align="center" style="background-color: #CDF7E0;">
        <td rowspan="2"><b>Заказчик (адрес)</b></td>
        <td rowspan="2"><b>№ заказа</b></td>
        <td colspan="<?=count($this->data['dates'])?>"><b>Платежи</b></td>
        <td colspan="3"><b>Сводка</b></td>
    </tr>
    <tr style="background-color: #CDF7E0;">
        <?php foreach ($this->data['dates'] as $date): ?>
            <td><b><?=date_create($date)->format('d.m.Y')?></b></td>
        <?php endforeach;?>
        <td><b>Стоимость</b></td>
        <td><b>Оплачено</b></td>
        <td><b>Остаток</b></td>
    </tr>
        <?php foreach ($this->data['list'] as $row): ?>
            <tr><td colspan="<?=5+count($this->data['dates'])?>" style="background-color: silver;">
                Менеджер: <b><?=$row['creator_name']?></b>
            </td></tr>
            <?php foreach ($row['orders'] as $i => $order): ?>
                <tr>
                    <?php $address = $order['customer'] .' (' . $order['address'] . ')'; ?>
                    <td><span class="address" title="<?=$address?>"><?=$address?></span></td>
                    <td><?=$order['order_id']?></td>
                    <?php foreach ($this->data['dates'] as $date) {
                        echo generatePaymentCell($date, $order['payments']);
                    } ?>
                    <td align="right">
                        <?php
                            echo number_format($order['cost'], 2, '.', '') . '&nbsp;р.';
                            $totalCost += $order['cost'];
                        ?>
                    </td>
                    <td align="right">
                        <?php
                            $summ = 0;
                            foreach ($order['payments'] as $p) {
                                if ($p['status'] == 1) {
                                    $summ += $p['summ'];
                                }
                            }
                            echo number_format($summ, 2, '.', '') . '&nbsp;р.';
                            $totalPayed += $summ;
                        ?>
                    </td>
                    <td align="right">
                        <?php
                            $rest = intVal($order['cost']) - $summ;
                            $totalRest += $rest;
                            echo number_format($rest, 2, '.', '') . '&nbsp;р.';
                        ?>
                    </td>
                </tr>
            <?php endforeach;?>
        <?php endforeach;?>
        <tr><td colspan="<?=5+count($this->data['dates'])?>" style="background-color: silver;"></td></tr>
        <tr align="right">
            <td colspan="<?=2+count($this->data['dates'])?>"><b>ИТОГО:</b></td>
            <td><?=number_format($totalCost, 2, '.', '')?>&nbsp;р.</td>
            <td><?=number_format($totalPayed, 2, '.', '')?>&nbsp;р.</td>
            <td style="background-color: yellow;"><?=number_format($totalRest, 2, '.', '')?>&nbsp;р.</td>
        </tr>
</table>
<?php endif; ?>

<?php
function generatePaymentCell($date, $payments) {

    $out = '&nbsp;';
    $class = '';
    $today = date_create();
    $today->setTime(0,0,0);
    $isDelayed = $today > date_create($date);

    foreach ($payments as $p) {
        if ($p['date'] == $date) {
            $out = $p['summ'] . '&nbsp;р.';
            $status = intVal($p['status']);
            $class = ($status) ? 'x-row-payed' : 'x-row-waiting';
            if ($isDelayed && !$status) {
                $class = 'x-row-paymentdelayed';
            }
        }
    }
    return '<td align="right" class="' . $class . '">' . $out . '</td>';
}
?>