<pre>
<?php //print_r($this->data); //die;?>
</pre>

<style>
.square {
    border: 1px solid grey;
    width: 20px;
}
.x-row-waiting {
    background: #99CC00;
}
.x-row-payed {
    background: #FF8080;
}
.x-row-confirmwaiting {
    background: #C0C0C0;
}
.x-row-paymentdelayed {
    background: #FF0000;
}
</style>

<table id="legend" cellspacing="0" cellpadding="0" border="0"><tr>
<td><b>Условные обозначения:&nbsp;</b></td>
<td class="square x-row-waiting">&nbsp;</td><td>&nbsp;Ожидается&nbsp;</td>
<td class="square x-row-payed">&nbsp;</td><td>&nbsp;Оплачено&nbsp;</td>
<td class="square x-row-confirmwaiting">&nbsp;</td><td>&nbsp;Ждем подтверждения&nbsp;</td>
<td class="square x-row-paymentdelayed">&nbsp;</td><td>&nbsp;Задерживается оплата&nbsp;</td>
</tr></table>

<center>
<h3>ГРАФИК ПЛАТЕЖЕЙ</h3>
</center>
<?php if (!empty($this->data['list']) && !empty($this->data['dates'])): ?>
<?php $totalSums = array_fill_keys($this->data['dates'], 0); ?>
<table cellspacing="0" cellpadding="5" border="1">
    <tr valign="middle" align="center" style="background-color: #CDF7E0;">
        <td rowspan="2"><b>Менеджер</b></td>
        <td rowspan="2"><b>Заказчик (адрес)</b></td>
        <td rowspan="2"><b>№ заказа</b></td>
        <td colspan="<?=count($this->data['dates'])?>"><b>Платежи</b></td>
        <td rowspan="2"><b>Сумма</b></td>
    </tr>
    <tr style="background-color: #CDF7E0;">
        <?php foreach ($this->data['dates'] as $date): ?>
            <td><b><?=date_create($date)->format('d.m.Y')?></b></td>
        <?php endforeach;?>
    </tr>
        <?php foreach ($this->data['list'] as $row): ?>
            <?php foreach ($row['orders'] as $i => $order): ?>
                <tr valign="middle">
                <?php if ($i == 0): ?>
                    <td rowspan="<?=count($row['orders'])?>"><?=$row['creator_name']?></td>
                <?php endif;?>
                    <td><?=$order['customer']?> (<?=$order['address']?>)</td>
                    <td><?=$order['order_id']?></td>
                    <?php foreach ($this->data['dates'] as $date) {
                        echo generatePaymentCell($date, $order['payments']);
                    } ?>
                    <td align="right">
                        <?php
                            $summ = 0;
                            foreach ($order['payments'] as $p) {
                                $summ += $p['summ'];
                                $totalSums[$p['date']] += $p['summ'];
                            }
                        echo number_format($summ, 2, '.', '') . '&nbsp;р.';
                        ?>
                    </td>
                </tr>
            <?php endforeach;?>
            <tr><td colspan="<?=4+count($this->data['dates'])?>" style="background-color: black;"></td></tr>
        <?php endforeach;?>
        <tr align="right">
            <td colspan="3"><b>ИТОГО:</b></td>
            <?php $summ = 0; ?>
            <?php foreach ($totalSums as $ts): ?>
                <?php $summ += $ts; ?>
                <td><?=number_format($ts, 2, '.', '')?>&nbsp;р.</td>
            <?php endforeach;?>
            <td style="background-color: yellow;"><?=number_format($summ, 2, '.', '')?>&nbsp;р.</td>
        </tr>
</table>
<?php endif; ?>

<?php function generatePaymentCell($date, $payments) {

    $today = date_create();
    $today->setTime(0,0,0);

    foreach ($payments as $p) {
        if ($p['date'] == $date) {
            $class = '';
            $status = intval($p['status']);

            if (($today > date_create($date)) && $status != 1) {
                $status = 3;
            };
            switch($status) {
                case 0: $class = 'x-row-waiting'; break;
                case 1: $class = 'x-row-payed'; break;
                case 2: $class = 'x-row-confirmwaiting'; break;
                case 3: $class = 'x-row-paymentdelayed'; break;
            }
            return '<td align="right" class="' . $class . '">' . $p['summ'] . '&nbsp;р.</td>';
        } else {
            return '<td>&nbsp;</td>';
        }
    }
} ?>