<style>
table {
	border-spacing: 0;
}
td {
	padding: 5px;
}
</style>

<div align="center">
<h3>
    Отчёт о затратах за период
    с <?
        $date = @date_create($this->data['start']);
        echo !$date ? '' : $date->format(OSDN_DATE_DISPLAY_FORMAT);
    ?>
    по <?
        $date = @date_create($this->data['end']);
        echo !$date ? '' : $date->format(OSDN_DATE_DISPLAY_FORMAT);
    ?>
</h3>

<table border=1 width="100%">
    <tr valign="bottom" align="center">
        <td width="150"><b>Дата</b></td>
        <td width="150"><b>Категория</b></td>
        <td width="150"><b>Статья</b></td>
        <td width="150"><b>Сумма</b></td>
        <td width="150"><b>№ заказа</b></td>
        <td><b>Комментарий</b></td>
    </tr>
        <?php
        $summTotal = 0;
        foreach ($this->data['rows'] as $row) :?>
            <tr>
                <td><?=$row['date']?></td>
                <td><?=$row['category']?></td>
                <td><?=$row['entry']?></td>
                <td align="right"><?=$row['summ']?>,00</td>
                <td align="right"><?=$row['order_id']?></td>
                <td><?=$row['comment']?></td>
            </tr>
        <?php
        $summTotal = $summTotal + $row['summ'];
        endforeach;?>
    <tr>
        <td colspan="3"><b>Итого:</b></td>
        <td align="right"><b><?=$summTotal?>,00</b>
        <td colspan="2"></td>
    </td></tr>
</table>

</div>

<pre>
<?php //print_r($this->data);?>
</pre>