<script type="text/javascript">
    xlib.username = '<?=$this->username; ?>';
    xlib.rolename = '<?=$this->rolename; ?>';
    xlib.roleId = '<?=$this->roleId; ?>';
</script>

<?php if (true === $this->showNotice): ?>

    <script>
        xlib.onReady(function() {
            new PMS.Notice.Show({
                items:[{
                    html: '<?php echo $this->notice; ?>'
                }]
            });
        });
    </script>

<?php endif;?>