<script type="text/javascript">
OSDN.applicationInitialization(function() {
    Ext.ns('PMS');
    PMS.Layout = new OSDN.Layout.Workspace({
        username: '<?=$this->username; ?>',
        rolename: '<?=$this->rolename; ?>'
    });
    PMS.Layout.getTabPanel().add({
        iconCls: 'orders-icon',
        closable: false,
        xtype: 'PMS.Orders.Layout',
        id: 'PMS.Orders.Layout'
    });
    PMS.Layout.doLayout();
});
</script>