<?php
    $PERIODS = array('hour' => 'Почасовая', 'day' => 'Подённая', 'month' => 'Cтавка')
?>
<center>
<h3>
    Отчёт о зарплате сотрудников за период
    с <?
        $date = @date_create($this->data['start']);
        echo !$date ? '' : $date->format(OSDN_DATE_DISPLAY_FORMAT);
    ?>
    по <?
        $date = @date_create($this->data['end']);
        echo !$date ? '' : $date->format(OSDN_DATE_DISPLAY_FORMAT);
    ?>
</h3>

<table cellspacing="0" cellpadding="5" border="1">
    <tr valign="bottom" align="center">
        <td><b>Сотрудник</b></td>
        <td><b>Должность</b></td>
        <td><b>Текущая система оплаты</b></td>
        <td><b>Текущий тариф (руб.)</b></td>
        <td><b>Отработанных часов</b></td>
        <td><b>Сумма оплаты (руб.)</b></td>
    </tr>
        <?php foreach ($this->data['rows'] as $row) :?>
            <tr>
                <td><?=$row['name']?></td>
                <td><?=$row['function']?></td>
                <td><?=$PERIODS[$row['period']]?></td>
                <td align="right"><?=$row['rate']?>,00</td>
                <td align="right"><?=$row['hours_total']?></td>
                <td align="right"><?=$row['summ_total']?>,00</td>
            </tr>
        <?php endforeach;?>
</table>

</center>

<pre>
<?php //print_r($this->data);?>
</pre>