DROP TABLE IF EXISTS `orders_budget`;
CREATE TABLE IF NOT EXISTS `orders_budget` (
  `id` int(10) unsigned NOT NULL auto_increment,
  `order_id` int(10) unsigned NOT NULL,
  `f1_qty` varchar(255) default NULL,
  `f1_price` varchar(255) default NULL,
  `f2_dest` varchar(255) default NULL,
  `f2_distance` varchar(255) default NULL,
  `f2_qty` varchar(255) default NULL,
  `f2_price` varchar(255) default NULL,
  `f3_transport` varchar(255) default NULL,
  `f3_people` varchar(255) default NULL,
  `f3_qty` varchar(255) default NULL,
  `f3_price` varchar(255) default NULL,
  `f4_people` varchar(255) default NULL,
  `f4_days` varchar(255) default NULL,
  `f4_qty` varchar(255) default NULL,
  `f4_price` varchar(255) default NULL,
  `f5_people` varchar(255) default NULL,
  `f5_days` varchar(255) default NULL,
  `f5_qty` varchar(255) default NULL,
  `f5_price` varchar(255) default NULL,
  `f6_params` varchar(255) default NULL,
  `f6_qty` varchar(255) default NULL,
  `f6_price` varchar(255) default NULL,
  `f7_params` varchar(255) default NULL,
  `f7_qty` varchar(255) default NULL,
  `f7_price` varchar(255) default NULL,
  `f8_people` varchar(255) default NULL,
  `f8_days` varchar(255) default NULL,
  `f8_qty` varchar(255) default NULL,
  `f8_price` varchar(255) default NULL,
  `f9_params` varchar(255) default NULL,
  `f9_qty` varchar(255) default NULL,
  `f9_price` varchar(255) default NULL,
  `f10_qty` varchar(255) default NULL,
  `f10_price` varchar(255) default NULL,
  `f11_dest` varchar(255) default NULL,
  `f11_distance` varchar(255) default NULL,
  `f11_qty` varchar(255) default NULL,
  `f11_price` varchar(255) default NULL,
  `f12_people` varchar(255) default NULL,
  `f12_days` varchar(255) default NULL,
  `f12_qty` varchar(255) default NULL,
  `f12_price` varchar(255) default NULL,
  `f13_people` varchar(255) default NULL,
  `f13_days` varchar(255) default NULL,
  `f13_qty` varchar(255) default NULL,
  `f13_price` varchar(255) default NULL,
  `f14_qty` varchar(255) default NULL,
  `f14_price` varchar(255) default NULL,
  `f15_descr` varchar(255) default NULL,
  `f15_qty` varchar(255) default NULL,
  `f15_price` varchar(255) default NULL,
  `f16_descr` varchar(255) default NULL,
  `f16_qty` varchar(255) default NULL,
  `f16_price` varchar(255) default NULL,
  `f17_descr` varchar(255) default NULL,
  `f17_qty` varchar(255) default NULL,
  `f17_price` varchar(255) default NULL,
  PRIMARY KEY  (`id`),
  KEY `order_id` (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;


ALTER TABLE `orders_budget`
  ADD CONSTRAINT `orders_budget_ibfk_1` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;