<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" href="<?=$this->baseUrl(); ?>/css/icons.css" type="text/css" />
    <link rel="stylesheet" href="<?=$this->baseUrl(); ?>/css/system.css" type="text/css" />
    <link rel="stylesheet" href="<?=$this->baseUrl(); ?>/css/start.css" type="text/css" />
</head>
<body>
    <script src="<?=$this->baseUrl(); ?>/js/Library/OSDN/LoadingMask.js" type="text/javascript" ></script>
    <script type="text/javascript" >OSDN.LoadingMask.show();</script>

    <link rel="stylesheet" href="<?=$this->baseUrl(); ?>/js/Library/extjs/framework/resources/css/ext-all.css" />
    <script src="<?=$this->baseUrl(); ?>/js/Library/extjs/framework/adapter/ext/ext-base.js" type="text/javascript" ></script>
    <script src="<?=$this->baseUrl(); ?>/js/Library/extjs/framework/ext-all.js" type="text/javascript" ></script>
    <script src="<?=$this->baseUrl(); ?>/js/Library/extjs/framework/ext-lang-ru.js" type="text/javascript" ></script>

    <script src="<?=$this->baseUrl(); ?>/js/Library/OSDN/OSDN.js" type="text/javascript" ></script>
    <script src="<?=$this->baseUrl(); ?>/js/Library/OSDN/Translation.js" type="text/javascript" ></script>
    <script src="<?=$this->baseUrl(); ?>/js/Library/OSDN/form/PasswordField.js" type="text/javascript" ></script>
    <script src="<?=$this->baseUrl(); ?>/js/Library/extjs/ux/LoginDialog/LoginDialog.js" type="text/javascript" ></script>

    <script type="text/javascript">
    	Ext.BLANK_IMAGE_URL = '/js/Library/extjs/framework/resources/images/default/s.gif';
        OSDN.BASE_PATH	= '<?=$this->baseUrl(); ?>';
        OSDN.LOCALE 	= '<?=$this->locale; ?>';
        OSDN.DEBUG 		= <?=$this->debug ? 'true' : 'false'; ?>;

        link = function(module, controller, action, params) {
            if (true === /\.js$/.test(module)) {
                return OSDN.BASE_PATH + module;
            }

            var p = [];
            for (k in params) {
                if (k != 'responseType') {
                    p.push(k);
                    p.push(params[k]);
                }
            }

            var type = 'json';
            if (params && params.responseType) {
                type = params.responseType;
            }
            if (type == '') {
                return [OSDN.BASE_PATH, module, controller, action].join('/') + '/' + p.join('/');
            }
            return [OSDN.BASE_PATH, type, module, controller, action].join('/') + '/' + p.join('/');
        };

        var translation = new OSDN.Translation({locale: OSDN.LOCALE});
        translation.parse(OSDN.Translation.Storage);
        lang = function() {
            return translation.translate.createDelegate(translation, arguments)();
        };

		Ext.onReady(function() {
		    OSDN.LoadingMask.hide();
		    Ext.QuickTips.init();
		    var loginConfig = {
		        url: link('default', 'authenticate', 'login'),
		        basePath: OSDN.BASE_PATH + '/js/Library/extjs/ux/LoginDialog',
		        success: function() {
		            window.location.reload();
		        },
		        usernameVtype: '',
		        passwordVtype: '',
		        title: 'Авторизация',
		        message: 'Вход в систему',
		        failMessage: 'Вход невозможен',
		        waitMessage: 'Авторизация в системе...',
		        loginButtonText: 'Войти',
		        usernameLabel: 'Логин',
		        passwordLabel: 'Пароль'
		    };

            <?if ($this->debug): ?>
                Ext.apply(loginConfig, {
		            listeners: {
		            	show: function() {
		            		this._formPanel.getForm().loadRecord(new Ext.data.Record({
						    	username: '<?= $this->auth['username']; ?>',
						    	password: '<?= $this->auth['password']; ?>'
						    }));
		            	}
		            }
				});
			<?endif; ?>
		    new Ext.ux.albeva.LoginDialog(loginConfig).show();
		});
	</script>
</body>
</html>